### ISSUE TITLE
lunch groups don't close if not +1'd

### ISSUE THREAD

**Issue by ahwagner** [perlgatory/lunchinator#19]
This is bad. Not only are you friendless, but you are leaving cruft in our otherwise pristine database.

**Comment by ahwagner** [comment]
all lunch groups set to `departed`

**Comment by ahwagner** [comment]
okay, but lunch groups still don't depart if not +1'd. Which means that messages never update.

**Comment by tmooney** [comment]
Inspired by #32, the message here should get replaced.  I propose something like:

```<@$USER> wanted $DESTINATION at $TIME, but was eaten by a :kraken:.```

**Comment by tmooney** [comment]
I neglected to put "Closes #19" in #38, so I'll close it now :smile:
