### ISSUE TITLE
The /lunch command should accept a departure time

### ISSUE THREAD

**Issue by acoffman** [perlgatory/lunchinator#3]
Right now, it just checks for reactions after a hardcoded time window. Accept a departure time in the initial slash command and create the group DM ~5 (10?) minutes before the scheduled departure time. We discussed using the chronic gem for this: https://github.com/mojombo/chronic

**Comment by ahwagner** [comment]
we'll want to chop off the leading "at" when present so that Chronic will understand times when given with "at":

`' aT noon'.strip.gsub(/^*at\s+/i, '')` => `"noon"`

**Comment by ahwagner** [comment]
This is in progress at: https://github.com/perlgatory/lunchinator/tree/issue-3

**Comment by ahwagner** [comment]
This might work now. See https://github.com/perlgatory/lunchinator/commit/23c4aca200896a8e77f448658b0c59e00265c9b3

**Comment by ahwagner** [comment]
I declare this completed.
