### ISSUE TITLE
the /lunch should suggest possible destinations

### ISSUE THREAD

**Issue by kkrysiak** [perlgatory/lunchinator#9]

**Comment by kkrysiak** [comment]
Based on party size, suggest a handful of options.

**Comment by kkrysiak** [comment]
Using the Google Places API to get restaurant information and fill restaurant table. https://developers.google.com/places/web-service/search

**Comment by susannasiebert** [comment]
We will probably want lunchinator to execute a slash command for the simple poll to start a poll on a set of random places. Here is some documentation for an unofficial API endpoint that can achieve that: https://github.com/ErikKalkoken/slackApiDoc/blob/master/chat.command.md

**Comment by ahwagner** [comment]
For next time:

- run the populate job on live app
- add admin interface for managing restaurants (CRUD operation overview)

**Comment by susannasiebert** [comment]
"add admin interface for managing restaurants (CRUD operation overview)" should be its own github issue
